---
title: 'Mountain Pine Beetle GYE Projections'
author: "Stephen Huysman"
date: "`r Sys.Date()`"
fontsize: 10pt 
bibliography: beetle.bib
csl: global-ecology-and-biogeography.csl
output:
  html_document:
    toc: false
    toc_float: false
---

```{css, echo=FALSE}
body .main-container {
    max-width: 1080px !important;
    width: 1080px !important;
}
body {
    max-width: 1080px !important;
}
```

Accumulation of >833C (= 1106.15K) degree days (GDD) can allow mountain pine beetle (MPB) populations in mountainous regions to fully develop a new generation in a single year (univoltinism), as opposed to developing over several years (semivoltinism).  This has the potential to allow MPB outbreaks to become more severe.  Here, we show projections of beetle GDD in the Greater Yellowstone Ecosystem out to the end of the century.  Areas below this 1106.15K GDD threshold are shown, and areas exceeding it are hidden, in order to highlight the areas where beetle populations are likely to remaine semivoltine.  Lower GDD values would be associated with slower beetle development, and thus would be less likely to experience severe outbreaks of MPB.  

Three methods are shown:

1. Years exceeding the 1106.15K GDD threshold over the periods shown, averaged across all GCMs.  Beetle populations can exceed this threshold for a single year without resulting in a severe outbreak, but several years in sequence are likely to result in high tree mortality [@shanahanWhitebarkPineMortality2016]
2. Average GDD values across the periods shown, across all GCMs
3. Maximum GDD value projected by any GCM in the period shown.  This indicates whether a given pixel is likely to experience a single year above the GDD threshold across the period of interest.

GDD is calculated using a base temperature of 5.5C
max(0, T - 5.5)

GDD is summed across beetle development year - 1 August - 31 July, Following @buotteClimateInfluencesWhitebark2016

Years correspond to years of beetle development, not calendar years.  See figure at bottom for display of how calendar dates are mapped to "beetle years."

The dark grey line shows the GYE boundary, the thin blue line shows existing whitebark pine distribution from https://whitebarkfound.org/our-work/national-whitebark-pine-restoration-plan/data/

[Source code](https://github.com/shuysman/beetle_gdd)

``` {R, fig.height = 14, fig.width = 14, out.width = '100%', warning = FALSE, message = FALSE, echo = FALSE}
library(terra)
library(tidyterra)
library(ggmap)
library(sf)
library(smoothr)
library(glue)
library(tidyverse)

gdd_thresh <- 833 + 273.15

gye_boundary <- st_read("/home/steve/OneDrive/whitebark/gyeboundary/GYE_boundary_dd.shp", quiet = TRUE)
extent <- ext(gye_boundary)

wbp_existing <- rast("/home/steve/OneDrive/whitebark/data/existing/wbp_existing.tif")
wbp_existing <- terra::project(wbp_existing, crs(gye_boundary))
wbp_existing_poly <- smooth(terra::as.polygons(wbp_existing), method = "chaikin")

base_map <- get_stamenmap(bbox = c(left = extent[1][[1]],
                                    bottom = extent[3][[1]],
                                    right = extent[2][[1]],
                                    top = extent[4][[1]]),
          maptype = "terrain", 
          crop = TRUE,
          zoom = 7)

data_dir <- file.path("/media/smithers/shuysman/data/out/beetle/")

rcp45_rast <- rast(list.files(data_dir, ".*rcp45.*nc", full.names = TRUE))
rcp85_rast <- rast(list.files(data_dir, ".*rcp85.*nc", full.names = TRUE))

## rcp45_ensmean <- terra::tapp(rcp45_rast, index = "years", fun = "mean")
## rcp85_ensmean <- terra::tapp(rcp85_rast, index = "years", fun = "mean")

## rcp45_ensmin <- terra::tapp(rcp45_rast, index = "years", fun = "min")
## rcp85_ensmin <- terra::tapp(rcp85_rast, index = "years", fun = "min")

## rcp45_ensmax <- terra::tapp(rcp45_rast, index = "years", fun = "max")
## rcp85_ensmax <- terra::tapp(rcp85_rast, index = "years", fun = "max")

lyr_names <- c("2007-2024", "2025-2049", "2050-2074", "2075-2099")

rcp45_thresh <- terra::tapp(rcp45_rast >= gdd_thresh, index = "years", fun = "mean")
rcp85_thresh <- terra::tapp(rcp85_rast >= gdd_thresh, index = "years", fun = "mean")

rcp45_25yr_thresh_sum <- terra::tapp(rcp45_thresh, index = function(x) x %/% 25, fun = "sum")
rcp85_25yr_thresh_sum <- terra::tapp(rcp85_thresh, index = function(x) x %/% 25, fun = "sum")
names(rcp45_25yr_thresh_sum) <- lyr_names
names(rcp85_25yr_thresh_sum) <- lyr_names

ggmap(base_map) +
    geom_spatraster(data = clamp(rcp45_25yr_thresh_sum, 0, 5, values = FALSE), alpha = 0.85) +
    facet_wrap(~lyr) +
    geom_sf(data = gye_boundary, inherit.aes = FALSE, fill = NA, lwd = 1.5) +
    geom_sf(data = wbp_existing_poly, inherit.aes = FALSE, fill = NA, lwd = 0.25, color = "blue") +
    labs(fill = glue("Years above {gdd_thresh}K GDD Threshold")) +
    scale_fill_viridis_c(option = "H", na.value = NA) +
    ggtitle(glue("Areas w/ fewer than 5 years above {gdd_thresh}K GDD Threshold, rcp45 25 year")) +
    theme(axis.text = element_text(size = 8))

ggmap(base_map) +
    geom_spatraster(data = clamp(rcp85_25yr_thresh_sum, 0, 5, values = FALSE), alpha = 0.85) +
    facet_wrap(~lyr) +
    geom_sf(data = gye_boundary, inherit.aes = FALSE, fill = NA, lwd = 1.5) +
    geom_sf(data = wbp_existing_poly, inherit.aes = FALSE, fill = NA, lwd = 0.25, color = "blue") +
    labs(fill = glue("Years above {gdd_thresh}K GDD Threshold")) +
    scale_fill_viridis_c(option = "H", na.value = NA) +
    ggtitle(glue("Areas w/ fewer than 5 years above {gdd_thresh}K GDD Threshold, rcp85 25 year"))

rcp45_25yr_mean <- terra::tapp(rcp45_rast, index = function(x) x %/% 25, fun = "mean")
names(rcp45_25yr_mean) <- lyr_names
rcp85_25yr_mean <- terra::tapp(rcp85_rast, index = function(x) x %/% 25, fun = "mean")
names(rcp85_25yr_mean) <- lyr_names

rcp45_25yr_max <- terra::tapp(rcp45_rast, index = function(x) x %/% 25, fun = "max")
names(rcp45_25yr_max) <- lyr_names
rcp85_25yr_max <- terra::tapp(rcp85_rast, index = function(x) x %/% 25, fun = "max")
names(rcp85_25yr_max) <- lyr_names

ggmap(base_map) +
    geom_spatraster(data = clamp(rcp45_25yr_mean, 0, 833 + 273.15, values = FALSE), alpha = 0.85) +
    facet_wrap(~lyr) +
    geom_sf(data = gye_boundary, inherit.aes = FALSE, fill = NA, lwd = 1.5) +
    geom_sf(data = wbp_existing_poly, inherit.aes = FALSE, fill = NA, lwd = 0.25, color = "blue") +
    labs(fill = "Beetle Year GDD") +
    scale_fill_viridis_c(option = "H", na.value = NA) +
    ggtitle(glue("Beetle year GDD below {gdd_thresh}K threshold , rcp45 25 year averages"))

ggmap(base_map) +
    geom_spatraster(data = clamp(rcp85_25yr_mean, 0, 833 + 273.15, values = FALSE), alpha = 0.85) +
    facet_wrap(~lyr) +
    geom_sf(data = gye_boundary, inherit.aes = FALSE, fill = NA, lwd = 1.5) +
    geom_sf(data = wbp_existing_poly, inherit.aes = FALSE, fill = NA, lwd = 0.25, color = "blue") +
    labs(fill = "Beetle Year GDD") +
    scale_fill_viridis_c(option = "H", na.value = NA) +
    ggtitle(glue("Beetle year GDD below {gdd_thresh}K threshold}, rcp85 25 year averages"))

ggmap(base_map) +
    geom_spatraster(data = clamp(rcp45_25yr_max, 0, 833 + 273.15, values = FALSE), alpha = 0.85) +
    facet_wrap(~lyr) +
    geom_sf(data = gye_boundary, inherit.aes = FALSE, fill = NA, lwd = 1.5) +
    geom_sf(data = wbp_existing_poly, inherit.aes = FALSE, fill = NA, lwd = 0.25, color = "blue") +
    labs(fill = "Beetle Year GDD") +
    scale_fill_viridis_c(option = "H", na.value = NA) +
    ggtitle(glue("Beetle year GDD below {gdd_thresh}K threshold, rcp45 25 year maximum"))

ggmap(base_map) +
    geom_spatraster(data = clamp(rcp85_25yr_max, 0, 833 + 273.15, values = FALSE), alpha = 0.85) +
    facet_wrap(~lyr) +
    geom_sf(data = gye_boundary, inherit.aes = FALSE, fill = NA, lwd = 1.5) +
    geom_sf(data = wbp_existing_poly, inherit.aes = FALSE, fill = NA, lwd = 0.25, color = "blue") +
    labs(fill = "Beetle Year GDD") +
    scale_fill_viridis_c(option = "H", na.value = NA) +
    ggtitle(glue("Beetle year GDD below {gdd_thresh}K threshold, rcp85 25 year maximum"))
```


``` {R beetle-years, fig.height = 3, fig.width = 12, out.width = '100%', echo = FALSE, warning = FALSE, message = FALSE, fig.cap = "Mapping of calendar years to 'beetle years' example"}
start_month <- 5
beetle_year <- function(x) {
    index <- ymd(x)
    index <- as.character(year(add_with_rollback(index, months(start_month))))
    prename <- "y_"
    return(paste0(prename, index))
}

ex_dates <- seq.Date(from = as.Date("2050-07-01"), to = as.Date("2051-08-31"), by = "days")
beetle_dates <- beetle_year(ex_dates)

ggplot(data.frame(ex_dates = ex_dates, beetle_dates = beetle_dates)) +
    geom_line(mapping = aes(x = ex_dates, y = beetle_dates)) +
    scale_x_date(date_breaks = "1 month")

##knitr::kable(cbind(as.character(ex_dates), beetle_dates))
```


# References
Computational efforts were performed on the Tempest High Performance Computing System, operated and supported by University Information Technology Research Cyberinfrastructure at Montana State University.

